### ISSUE TITLE
Cannot reproduce the reported performance

### ISSUE THREAD

**Issue by cvloverrrrrr** [canqin001/PointDAN#10]
Hello, thanks for your interesting and impressive work. However, when I try to run `main.sh` and reproduce your results, I find I cannot reproduce the reported performance on some adaptation scenarios (e.g., S->SS, SS->S, S->M) as the following table. Could you help me to solve this problem?

  | M->S | M->SS | S->M | S->SS | SS->M | SS->S | Avg
-- | -- | -- | -- | -- | -- | -- | --
Reported | 64.2 | 33.0 | 47.6 | 33.9 | 49.1 | 64.1 | 48.7
Repeat 1 | 60.53 | 31.0 | 49.28 | 27.03 | 48.92 | 60.49 | 46.21
Repeat 2 | 63.65 | 28.94 | 48.56 | 29.34 | 48.92 | 61.64 | 46.84

**Comment by canqin001** [comment]
Hi,
Thanks for your interest of our work. There is no self-training part in the released code. The directly comparable results should be 63.7, 32.1, 44.5, 33.7, 48.2, 63.0. By the way, the results of S->S* and M->S* are not quite stable. We suggest you run more times and would achieve similar results after that.

**Comment by cvloverrrrrr** [comment]
Hello, thanks for your explaination! It's really helpful for me!
