### ISSUE TITLE
Source codebase of train_source

### ISSUE THREAD

**Issue by MitalPattani** [canqin001/PointDAN#12]
@canqin001 If I understand correctly train_source is just an implementation of Pointnet where you have used source data for training and tested on target1 and target2 correct?
Can you also mention the source codebase if it is opensource?
I checked the author of paper 22 but their repository is in TensorFlow is that the only source?
Thank you in advance!

**Comment by canqin001** [comment]
Thanks for your advice! You are right. It's based on pointnet. For paper 22, I think there should be the pytorch code implemented by others. I am busy for NeurIPS right now. I will revise the repo after that.

**Comment by MitalPattani** [comment]
Umm okay, thanks but what advice are you talking about?

**Comment by canqin001** [comment]
I will mention the source code of pointnet in this repo later.

**Comment by canqin001** [comment]
Hi.
I have updated the repo. Our implementation of PointNet refers to  https://github.com/fxia22/pointnet.pytorch
