### ISSUE TITLE
Weight of src loss

### ISSUE THREAD

**Issue by HaoranTang** [canqin001/PointDAN#16]
Hi,

Just a really quick question that I notice for some source-target pairs we choose source loss weight=0.5 when training (i.e., train.py -source modelnet -target scannet  -scaler 1 -weight 0.5), while others start with weight 1. I wonder how this weight affect performance or all weight selections in main.sh are optimal. For the above example, what will be the difference if I do -source modelnet -target scannet  -scaler 1 -weight 1?

**Comment by canqin001** [comment]
Weight will affect the performance of our model. It's hard to say that is the optimal choice as we have not explored all the possible weights during the experiments. Of course you can take source modelnet -target scannet -scaler 1 -weight 1.
