### ISSUE TITLE
Questions about ScanNet-10 (S*)

### ISSUE THREAD

**Issue by wusuoweima** [canqin001/PointDAN#2]
I have read your paper, it is an interesting and good work.  But I have two questions as follow
1. I failed to isolate 10 classes instances from Scannet scene ( I isolate them from vh_clean_2.labels.ply and _vh_clean.aggregation.json).  Could you please share the method and the related code?
Looking forward to hearing from you. Thanks. 
2. Could you please tell me how to split the train dataset and test dataset of  ScanNet-10 (S*)
@canqin001

**Comment by Hxyou** [comment]
Hi,
We actually extract ScanNet data by partly borrowing from [PointCNN](https://github.com/yangyanli/PointCNN/tree/master/data_conversions).
No worry, we will release the data, code and extracting scripts together by the beginning of December.

**Comment by wusuoweima** [comment]
@Hxyou Thanks for your answer. Now I can isolate  instances from the  scene of Scannet's training set. But how to isolate  instances from the  scene of Scannet's testing set? I download the Scannet-v2, whose testing set dose not have _vh_clean_2.ply, _vh_clean_2.0.010000.segs.json and .aggregation.json.

**Comment by wusuoweima** [comment]
@Hxyou 
Thanks for your answer. Now I can isolate instances from the scene of Scannet's training set. But how to isolate instances from the scene of Scannet's testing set? I download the Scannet-v2, whose testing set dose not have _vh_clean_2.ply, _vh_clean_2.0.010000.segs.json and .aggregation.json.

**Comment by Hxyou** [comment]
Indeed! The ScanNet didn't provide label of testing data. So we use evaluation data as testing data in our code, which is the same as what PointCNN did in both object classification and segmentation.
