### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by antoalli** [canqin001/PointDAN#4]
Hi! I'm trying to use your dataset but i'm having very strange behaviours. Could you tell me the exact data augmentation you applied? Thank you

**Comment by canqin001** [comment]
Hi Antonio,

We apply the same data augmentation as those of PointNet.

Can Qin

**Comment by antoalli** [comment]
Hi Can,
thank you for your work and also for the fast reply. Further on, does the shapes in your datasets have been rotation aligned? I assume that the alignment for your ModelNet-10 (M) is a consequence of starting from ModelNet10 which is rotation aligned.. What about ShapeNet-10 (S)?
Thank you in advance

**Comment by wusuoweima** [comment]
Then, do you use the vote strategy when evaluate？

**Comment by wusuoweima** [comment]
Then, do you use the vote strategy when evaluate？
@canqin001 @Hxyou

**Comment by Hxyou** [comment]
@antoalli 
In ShapeNet and ModelNet, their data are aligned respectively by the owners. But we don't manually align these two datasets into the same rotation angle. Because we also consider the rotation as a kind of domain gap between different datasets.

**Comment by Hxyou** [comment]
@wusuoweima 
No, we don't use it.

**Comment by wusuoweima** [comment]
Are Modelnet10, ShapeNet10 and ScanNet10 argumented as those of PointNet?

**Comment by Hxyou** [comment]
@wusuoweima Yep, you're right.
