### ISSUE TITLE
Plant category of ShapeNet10

### ISSUE THREAD

**Issue by wusuoweima** [canqin001/PointDAN#5]
I have see your data. Dose the ShapeNet10 is a subset of shrec16/shrec17? But I do not how to get the plant category .

**Comment by Hxyou** [comment]
@wusuoweima 
We collect plant class from ShapeNetSem. It is a smaller subset consisting of 12,000 models but with broader 270 categories.

**Comment by wusuoweima** [comment]
@Hxyou 
Thank you for your  reply.  Are the other categories of shapent-10 collected from ShapeNetSem?

**Comment by Hxyou** [comment]
@wusuoweima 
Others are from shrec16/shrec17.
