### ISSUE TITLE
Question about output in Net_MDA

### ISSUE THREAD

**Issue by tsbiosky** [canqin001/PointDAN#6]
why their will be 2 pred resulit in Net_MDA
y1 = self.c1(x)
y2 = self.c2(x)

what is the difference between y1 and y2?

**Comment by canqin001** [comment]
This design follows the architecture of MCD[1] in which both y1 and y2 are outputs. There is a divergence loss by maximizing the l2 distance between softmax scores of y1 and y2 to enforce their difference.

[1] Maximum classifier discrepancy for unsupervised domain adaptation. K. Saito, K. Watanabe, Y. Ushiku, and T. Harada. CVPR18
