### ISSUE TITLE
Question about evaluation accuracy

### ISSUE THREAD

**Issue by brandon9838** [canqin001/PointDAN#7]
Hi, I'm trying to repeat your experiment and I want to make sure I'm doing it right. 
In the paper you mentioned that all the experiments have been repeated three times and the reported accuracy is the average top-1 classification accuracy.
So If I want to repeat the M→S experiment, I should execute 
python train.py -source modelnet -target shapenet -scaler 1 -weight 1 -tb_log_dir ./logs/sa_m2s
three times, and the average of the three Best Target Acc is the final accuracy. Do I understand it right? Thanks for replying!

**Comment by canqin001** [comment]
Hi. You are right. Just following the main.sh would be ok.
