### ISSUE TITLE
Question about Self-Adaptive Node Construction

### ISSUE THREAD

**Issue by godspeed1989** [canqin001/PointDAN#9]
Hi, can.
Thank you for your great job.
I encountered several questions when reading your paper and code.

The Eq.1 of your paper uses the feature from the neighbor points to sub the feature from the central point. 
![image](https://user-images.githubusercontent.com/2350713/75798849-24222200-5db2-11ea-9eb5-a77ad66277df.png)
However, i didn't find the corresponding code from `adapt_layer_off` module.

Again in `adapt_layer_off`, does self.residual represents the weight R
![image](https://user-images.githubusercontent.com/2350713/75798577-ba097d00-5db1-11ea-9d00-f430d1c5f92d.png). If so, what are the corresponding layers for R_G and R_T?

Thank you very much

**Comment by Hxyou** [comment]
@godspeed1989 
Eq.1 is described on Line 109 of model_utils.py
`group_fea = group_fea - fpoint_fea.unsqueeze(3).expand(-1, -1, -1, self.num_node)`
R_G corresponds to self.residual, R_T corresponds to self.pred_offset.

**Comment by godspeed1989** [comment]
Thank you.
